### ISSUE TITLE
Add a flag at package.json's start command --port

### ISSUE THREAD

**Issue by rianby64** [m3co/configs#3]
Currently every _package.json_ at router3, pseudoimport-html and so on... holds

```json
"scripts": {
  "start": "gulp",
}
```

But would be a great if _gulp_ allows to set a port. It could be something like
```json
"scripts": {
  "start": "gulp --port 9003",
}
```

**Comment by Anomeon** [comment]
Done

**Comment by rianby64** [comment]
Next time, please, close issue via commit's comment
